version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json
    schedule:
      interval: "daily"
      labels: "dependencies"
  - package-ecosystem: "github-actions"
    directory: .github/workflows
    schedule:
      interval: "daily"